version: 2.1
orbs:
  go: circleci/go@1.5.0
  slack: circleci/slack@4.10.1

jobs:
  # This job builds the hive executable and stores it in the workspace.
  build:
    docker:
      - image: cimg/go:1.18
    steps:
      # Build it.
      - checkout
      - go/load-cache
      - go/mod-download
      - go/save-cache
      - run: {command: "go build ."}
      # Store the executable.
      - persist_to_workspace:
          root: .
          paths: ["hive"]

  # The below job runs the optimism test simulations. This requires a virtual
  # machine instead of the container-based build environment because hive needs
  # to be able to talk to the docker containers it creates.
  run-hive-sim:
    machine:
      image: ubuntu-2004:202201-02
      docker_layer_caching: true
    parameters:
      sim:
        type: string
        default: optimism
        description: Sims to run
    steps:
      - checkout
      - attach_workspace: {at: "/tmp/build"}
      - run:
          command: |
            /tmp/build/hive \
            -sim=<<parameters.sim>> \
            -sim.loglevel=5 \
            -docker.pull=true \
            -client=go-ethereum,op-geth_optimism-history,op-proposer_develop,op-batcher_develop,op-node_develop |& tee /tmp/build/hive.log || echo "failed."
      - run:
          command: |
            tar -cvf /tmp/workspace.tgz -C /home/circleci/project /home/circleci/project/workspace
          name: "Archive workspace"
      - store_artifacts:
          path: /tmp/workspace.tgz
          destination: hive-workspace.tgz
      - run:
          command: "! grep 'pass.*=false' /tmp/build/hive.log"
      - slack/notify:
          channel: C03N11M0BBN
          event: fail
          template: basic_fail_1
      - slack/notify:
          channel: C03N11M0BBN
          event: pass
          template: basic_success_1

  # This job runs the go unit tests.
  go-test:
    docker:
      - image: cimg/go:1.18
    steps:
      # Get the source.
      - checkout
      - go/load-cache
      - go/mod-download
      - go/save-cache
      # Run the tests.
      - run:
          name: "hive module tests"
          command: "go test -cover ./..."
      - run:
          name: "hiveproxy module tests"
          command: "go test -cover ./..."
          working_directory: "./hiveproxy"
# some upstream simulators are broken, don't use latest, geth, etc.
#      - run:
#          name: "Compile Go simulators"
#          command: ".circleci/compile-simulators.sh"

workflows:
  main:
    jobs:
      - go-test
      - build
      - run-hive-sim:
          name: hive-test-l1ops
          requires: ["build"]
          context: slack
          sim: optimism/l1ops
      - run-hive-sim:
          name: hive-test-p2p
          requires: [ "build" ]
          context: slack
          sim: optimism/p2p
      - run-hive-sim:
          name: hive-test-rpc
          requires: [ "build" ]
          context: slack
          sim: optimism/rpc
      - run-hive-sim:
          name: hive-test-testnet
          requires: [ "build" ]
          context: slack
          sim: optimism/testnet
  scheduled:
    triggers:
      - schedule:
          # run every 4 hours
          cron: "0 0,4,8,12,16 * * *"
          filters:
            branches:
              only: [ "optimism" ]
    jobs:
      - build
      - run-hive-sim:
          requires: ["build"]
          context: slack